version: '3.9'

services:
  muzlag:
    volumes:
      - .:/muzlag
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
